apiVersion: apps/v1
kind: StatefulSet # Meant for stateful applications, guarantees about the ordering and uniqueness of pods
metadata:
  name: mongodb-statefulset
spec:
  serviceName: "mongodb-service"
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD # Must be called root
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: mongodb-password
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"] # Only one node can read/write simultaneously
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None # Headless service therefore no IP assigned to this service
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
